version: '3.8'
services:
  database:
    image: postgres:16-bookworm
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: insecure-local-only
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dev", "-d", "dev" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1s
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 250M
  migrator:
    build:
      context: .
      dockerfile: .docker/migrator.Dockerfile
    environment:
      DATABASE_CONNECTION_STRING: "dev:insecure-local-only@database:5432/dev"
    depends_on:
      database:
        condition: service_healthy
  backend:
    build:
      context: .
      dockerfile: .docker/backend.Dockerfile
    volumes:
      - .:/web
    entrypoint: uvicorn
    command: backend:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      DATABASE_CONNECTION_STRING: "dev:insecure-local-only@database:5432/dev"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.Dockerfile
      args:
        BACKEND_SERVER: backend:8000
    ports:
      - "80:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 25M
volumes:
  postgres_data:
