version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:80"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - web
