"""create example

Revision ID: 305d58f0050e
Revises: 6ea87a61a6e1
Create Date: 2024-06-10 22:12:02.684650

"""
from typing import Sequence


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305d58f0050e'
down_revision: str | None = '6ea87a61a6e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('example')
    # ### end Alembic commands ###
