"""init

Revision ID: 6ea87a61a6e1
Revises: 
Create Date: 2024-06-10 22:11:42.362007

"""
from typing import Sequence


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea87a61a6e1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
