name: Build Images, Migrate Database, and Deploy ECS Service

on:
  push:
    branches:
      - main

jobs:
  build-nginx:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Configure Amazon ECR credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build NGINX and push to ECR
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./.docker/nginx.Dockerfile
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ vars.AWS_ECR_NGINX_REPO }}:latest
        build-args: |
          FASTAPI_SERVER=localhost:8000

  build-api-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Configure Amazon ECR credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build API backend and push to ECR
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./.docker/backend.Dockerfile
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ vars.AWS_ECR_API_BACKEND_REPO }}:latest
        build-args: |
          DATABASE_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING_API }}
  
  migrate:
    runs-on: ubuntu-latest
    needs: [build-nginx, build-api-backend]
    permissions:
      contents: read

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Build image
        run: |
          docker build \
            . \
            -f .docker/migrator.Dockerfile \
            -t migrator \
            --build-arg="DATABASE_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING_MIGRATOR }}"
  
      - name: Run Migrations
        run: docker run migrator

  deploy:
    runs-on: ubuntu-latest
    needs: migrate

    steps:
    - name: Configure Amazon ECR credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        aws-region: ${{ vars.AWS_REGION }}
    
    - name: Deploy to Amazon ECS
      run: |
        aws ecs update-service --cluster ${{ vars.AWS_ECS_CLUSTER_NAME }} --service ${{ vars.AWS_ECS_SERVICE_NAME }} --force-new-deployment
