name: Build and Push Docker images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lower case repo name
      id: lowercase_repo_name
      run: echo "LOWERCASE_REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push Docker image for web
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.fastapi
        push: true
        tags: ghcr.io/${{ env.LOWERCASE_REPO_NAME }}/web:latest

    - name: Build and push Docker image for nginx
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.nginx
        push: true
        tags: ghcr.io/${{ env.LOWERCASE_REPO_NAME }}/nginx:latest
