name: Build and Push Docker images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image for web
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.fastapi
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name | toLower }}/web:latest

    - name: Build and push Docker image for nginx
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.nginx
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name | toLower }}/nginx:latest
