name: Build and Push Docker images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lower case repo name
      id: container_name
      run: echo "CONTAINER_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push Docker image for nginx
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./.docker/nginx.Dockerfile
        push: true
        tags: ghcr.io/${{ env.CONTAINER_NAME }}/nginx:latest
