name: Migrate Production Database

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Image
      run: docker build . -f .docker/migrator.Dockerfile -t migrator

    - name: Run Migrations
      run: |
        docker run \
          -e POSTGRES_HOST="${{ secrets.MIGRATOR_POSTGRES_HOST }}" \
          -e POSTGRES_AUTH="${{ secrets.MIGRATOR_POSTGRES_AUTH }}" \
          -e POSTGRES_DB="${{ secrets.MIGRATOR_POSTGRES_DB }}" \
          migrator
